127.0.0.1 - - [04/Jul/2023 08:46:43] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request        
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request        
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Mi unidad\Cursos\CodingDojo\python\flask_mysql\db_connection\miprimer_flask_mysql\server.py", line 8, in index
    friends = Friend.get_all()
              ^^^^^^^^^^^^^^^^
  File "G:\Mi unidad\Cursos\CodingDojo\python\flask_mysql\db_connection\miprimer_flask_mysql\friend.py", line 17, in get_all
    results = connectToMySQL('first_flask').query_db(query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Mi unidad\Cursos\CodingDojo\python\flask_mysql\db_connection\miprimer_flask_mysql\mysqlconnection.py", line 42, in connectToMySQL  
    return MySQLConnection(db)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\Mi unidad\Cursos\CodingDojo\python\flask_mysql\db_connection\miprimer_flask_mysql\mysqlconnection.py", line 4, in __init__
    connection = pymysql.connect(host = 'localhost',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\connections.py", line 968, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\connections.py", line 1062, in _process_auth      
    pkt = self._read_packet()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet        
    packet.raise_for_error()
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error        
    err.raise_mysql_exception(self._data)
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception       
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'first_flask'")
127.0.0.1 - - [04/Jul/2023 08:46:44] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [04/Jul/2023 08:46:44] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [04/Jul/2023 08:46:44] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [04/Jul/2023 08:46:44] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
 * Detected change in 'G:\\Mi unidad\\Cursos\\CodingDojo\\python\\flask_mysql\\db_connection\\miprimer_flask_mysql\\friend.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 136-775-512
127.0.0.1 - - [04/Jul/2023 08:47:54] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request        
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request        
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Mi unidad\Cursos\CodingDojo\python\flask_mysql\db_connection\miprimer_flask_mysql\server.py", line 8, in index
    friends = Friend.get_all()
              ^^^^^^^^^^^^^^^^
  File "G:\Mi unidad\Cursos\CodingDojo\python\flask_mysql\db_connection\miprimer_flask_mysql\friend.py", line 17, in get_all
    results = connectToMySQL('miprimer_flask_mysql').query_db(query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Mi unidad\Cursos\CodingDojo\python\flask_mysql\db_connection\miprimer_flask_mysql\mysqlconnection.py", line 42, in connectToMySQL  
    return MySQLConnection(db)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\Mi unidad\Cursos\CodingDojo\python\flask_mysql\db_connection\miprimer_flask_mysql\mysqlconnection.py", line 4, in __init__
    connection = pymysql.connect(host = 'localhost',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\connections.py", line 968, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\connections.py", line 1062, in _process_auth      
    pkt = self._read_packet()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet        
    packet.raise_for_error()
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error        
    err.raise_mysql_exception(self._data)
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception       
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'miprimer_flask_mysql'")
127.0.0.1 - - [04/Jul/2023 08:47:54] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [04/Jul/2023 08:47:54] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [04/Jul/2023 08:47:54] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [04/Jul/2023 08:47:54] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
 * Detected change in 'G:\\Mi unidad\\Cursos\\CodingDojo\\python\\flask_mysql\\db_connection\\miprimer_flask_mysql\\friend.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 136-775-512
127.0.0.1 - - [04/Jul/2023 08:48:21] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request        
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request        
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Mi unidad\Cursos\CodingDojo\python\flask_mysql\db_connection\miprimer_flask_mysql\server.py", line 8, in index
    friends = Friend.get_all()
              ^^^^^^^^^^^^^^^^
  File "G:\Mi unidad\Cursos\CodingDojo\python\flask_mysql\db_connection\miprimer_flask_mysql\friend.py", line 17, in get_all
    results = connectToMySQL('friends').query_db(query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Mi unidad\Cursos\CodingDojo\python\flask_mysql\db_connection\miprimer_flask_mysql\mysqlconnection.py", line 42, in connectToMySQL  
    return MySQLConnection(db)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\Mi unidad\Cursos\CodingDojo\python\flask_mysql\db_connection\miprimer_flask_mysql\mysqlconnection.py", line 4, in __init__
    connection = pymysql.connect(host = 'localhost',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\connections.py", line 968, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\connections.py", line 1062, in _process_auth      
    pkt = self._read_packet()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet        
    packet.raise_for_error()
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error        
    err.raise_mysql_exception(self._data)
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception       
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'friends'")
127.0.0.1 - - [04/Jul/2023 08:48:21] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [04/Jul/2023 08:48:21] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [04/Jul/2023 08:48:21] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [04/Jul/2023 08:48:21] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
 * Detected change in 'G:\\Mi unidad\\Cursos\\CodingDojo\\python\\flask_mysql\\db_connection\\miprimer_flask_mysql\\friend.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 136-775-512
Running Query: SELECT * FROM friends;
[]
127.0.0.1 - - [04/Jul/2023 08:48:50] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request        
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request        
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Mi unidad\Cursos\CodingDojo\python\flask_mysql\db_connection\miprimer_flask_mysql\server.py", line 10, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\templating.py", line 150, in render_template        
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\jinja2\environment.py", line 1010, in get_template        
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\jinja2\environment.py", line 969, in _load_template       
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.virtualenvs\miprimer_flask_mysql-qtHNpN1q\Lib\site-packages\flask\templating.py", line 98, in _get_source_fast        
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
127.0.0.1 - - [04/Jul/2023 08:48:50] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [04/Jul/2023 08:48:50] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [04/Jul/2023 08:48:50] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [04/Jul/2023 08:48:50] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
 * Detected change in 'G:\\Mi unidad\\Cursos\\CodingDojo\\python\\flask_mysql\\db_connection\\miprimer_flask_mysql\\server.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 136-775-512
Running Query: SELECT * FROM friends;
[]
127.0.0.1 - - [04/Jul/2023 08:50:22] "GET / HTTP/1.1" 200 -